### ISSUE TITLE
inputs.who-to-greet.required should be set to false since the parameter has a default value

### ISSUE THREAD

**Issue by ilyasotkov** [actions/hello-world-javascript-action#16]
I can use this Action without supplying any inputs and the default for `who-to-greet` input variable is "World". Why is it documented (in action.yml and README.md) as required? 

And more generally, why would [Metadata syntax for GitHub Actions
](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions) specification even allow `required: true` and `default` to be specified together?

**Comment by ncalteen** [comment]
Hello! Closing this out for now, but if you're still running into any kind of issue please reopen and let me know! I will try to respond soon as I can :)
