### ISSUE TITLE
Github Actions uses invalid environment variables.

### ISSUE THREAD

**Issue by shadycuz** [actions/hello-world-javascript-action#22]
I'm trying to test this action locally before creating my own. However the action only echo's `hello`. When I try to set the environment variable:

```
export INPUT_WHO-TO-GREET=test
bash: export: `INPUT_WHO-TO-GREET=test': not a valid identifier
```
It fails? It seems Github Actions allows `-` in its Environment variables but bash doesn't.

**Comment by jonatanlr98** [comment]
export INPUT_WHO-TO-GREET=test
bash: export: `INPUT_WHO-TO-GREET=test': not a valid identifier

**Comment by jonatanlr98** [comment]
https://github.com/actions/hello-world-javascript-action/issues/22#issue-897004047

**Comment by ncalteen** [comment]
When testing this locally, it looks like `@actions/core` library is looking for the `INPUT_WHO_TO_GREET` environment variable instead. Hyphens are being replaced with underscores. Let me know if that helps!

**Comment by ncalteen** [comment]
Hello! Closing this out for now, but if you're still running into any kind of issue please reopen and let me know! I will try to respond soon as I can :)
